# Generated by Django 3.1.4 on 2020-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodTitle', models.CharField(default='', max_length=50)),
                ('prodMarketPrice', models.IntegerField(default=0)),
                ('prodThcPrice', models.IntegerField(default=0)),
                ('prodCategory', models.CharField(default='', max_length=50)),
                ('prodSubCategory', models.CharField(default='', max_length=50)),
                ('productBrand', models.CharField(default='', max_length=50)),
                ('prodDescription', models.CharField(default='', max_length=500)),
                ('prodImage1', models.ImageField(default='', upload_to='thcProducts/images')),
                ('prodImage2', models.ImageField(default='', upload_to='thcProducts/images')),
                ('prodImage3', models.ImageField(default='', upload_to='thcProducts/images')),
                ('prodImage4', models.ImageField(default='', upload_to='thcProducts/images')),
                ('prodImage5', models.ImageField(default='', upload_to='thcProducts/images')),
                ('prodVideoLink', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
