# Generated by Django 3.1.4 on 2020-12-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thcProducts', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.CharField(max_length=1000000000000000000000000000000),
        ),
    ]
